### ISSUE TITLE
[SCIONLab] Remove zookeeper from SCIONLab VMs and SCION boxes

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-coord#106]
As discussed with @perrig zookeeper should be removed from SCIONLab ASes which run only one instance of each service (i.e. SCIONLab VMs, SCION boxes)

**Comment by kormat** [comment]
What zookeeper instance would the services use in that case?

**Comment by hausheer** [comment]
Zookeeper should be replaced altogether with a simple alternative. Since there is only one instance of each SCION service running on SCIONLab VMs and SCION boxes, the goal is to avoid the overhead of running zookeeper.

**Comment by kormat** [comment]
We are planning to remove zookeeper, but it's going to take a Lot of work to get there.
