### ISSUE TITLE
[SCIONLab] Automatically update topology figure

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#111]
The topology figure on the front page of the SCIONLab Coordination Service should be automatically updated in regular intervals.
In addition, it should contain names/labels for ISDs and ASes.

**Comment by jonghoonkwon** [comment]
I initiated a script code on the Scion-Web server, which generates a topology figure by parsing the 'gen' directory and uploads the latest figure to the Scion-coord server via SCP.
The script would automatically run every midnight.

**Comment by mlegner** [comment]
Great, that seems to do the trick!
In the long run it would probably be better if we didn't have to rely on scp and instead add an API on scion-coord. What do you think?
Is this script in a repository somewhere?
Also: Did you look into mechanisms to add names/labels for ISDs and ASes?

**Comment by chaehni** [comment]
What names/labels need to be added? At the moment ISDs and ASes are labelled with their number.

**Comment by perrig** [comment]
It would be great to have a short descriptor for each ISD / AS. The TRC
contains information you can display.
For ASes, we may need to have a separate file for now with a mapping, if
the information is not already in the certificate.

**Comment by matzf** [comment]
Implemented in [netsec-ethz/scionlab](https://github.com/netsec-ethz/scionlab).
