### ISSUE TITLE
[SCIONLab] Unified installation script for different platforms

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#114]
There should be one central script that handles the majority of the SCION setup for different platforms.
This script could then be called from the Vagrantfile, downloaded and executed by the user for a native setup, and be included in the Raspberry Pi and Odroid images.

**Comment by xabarass** [comment]
I'v finished the script. Its currently on my Gist as we haven't discussed where to put it. Basically when running the script one must specify path to gen directory, client.conf and also to directory with patch files (script will apply all patches files that are in specified directory).

https://gist.github.com/xabarass/7aa560a2ba9010d8dbb6f08029509ae5

**Comment by mlegner** [comment]
Fixed by (#130).
