### ISSUE TITLE
[SCIONLab] Support dynamic public IP addresses without VPN

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#115]
After the heartbeat API #109 is implemented, this could be used to support DynDNS-like support for dynamic public IP addresses that do not require an OpenVPN setup.

**Comment by hausheer** [comment]
@mlegner thanks for creating all the new issues. As discussed today, the plan is to use the AS private key to authenticate to the coordinator for reporting the new IP address.
