### ISSUE TITLE
Add scion-utilities as a submodule

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#116]
The Coordination Service relies on libraries from `scion-web` to create the gen folder.
Those should therefore get included as a submodule to `scion-coord`, ideally after putting them into a separate `scion-utilities` repository.

**Comment by jonghoonkwon** [comment]
As @mlegner and I discussed, all the libraries related with generating "gen" folder would be relocated to the "scion-utilities" repository.

**Comment by mlegner** [comment]
Fixed by #152.
