### ISSUE TITLE
Enable a host in local network to communicate with SCIONLab AS to access SCION network

### ISSUE THREAD

**Issue by perrig** [netsec-ethz/scion-coord#128]
The idea is that a SCIONLab AS (running on Virtualbox VM or Docker) can support SCION end hosts on the local network. We need to figure out which addresses to bind border router and services to, and how to enable SCION communication with the local host.

**Comment by mlegner** [comment]
If we have a VM setup, we will have to forward the ports of the different servers from the host machine to the VM in the Vagrantfile. Still, if we want to setup enhosts outside of the host machine, we will need to know the IP address of the host machine as well (this is also true for dedicated setups) -- this will probably require user interaction.
In general, would it make sense to have the servers listening on all interfaces (0.0.0.0)?

**Comment by xabarass** [comment]
I don't have lot of experience with this, but would it work if we create a dummy interface that always has the same IP and bridge eth0, vpn interfaces to it. Bridge will act as layer 2 switch. This way gen folder would be independent on platform. Maybe creating a NAT instead of the L2 switch?

**Comment by hausheer** [comment]
In my view, for the VM setup it would be sufficient (at least for the upcoming release) to enable access to SCION from within the host PC. By default Vagrant creates a subnet (10.0.2.0) between the host PC and the VM on which the VM can be accessed from the host PC at IP address 10.0.2.15. So the servers would need to listen on that interface.
For the PC engines, one separate subnet is currently created for each additional eth ports, so the servers would need to listen on each of those. 
Finally, for the raspberriPi (where we have two interfaces: eth and wifi) it would be nice if the user would be able to configure the setup on the SCION coordinator (i.e. determine which interface is used as uplink and which one is used as local interface)
