### ISSUE TITLE
Move registration, login and logout to the server side

### ISSUE THREAD

**Issue by silenteh** [netsec-ethz/scion-coord#13]
Handling of the registration and login works fine with angular, however, once the user logs out the XSRF token needs to be regenerated. This seems to cause several issues.
One solution would be to refresh the login page, after a user logged out, however I think it's a better idea to move the whole logic on the server side and keep the angular application only for the administration part. (after logging in)

**Comment by mlegner** [comment]
This has been fixed in the meantime.
