### ISSUE TITLE
Do not regenerate certificates for SCIONLabAS on updates

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#135]
Currently, all credentials are regenerated when the user changes their AS configuration.
This leads to problems due to the caching of certificates in other ASes.
In the future, we should only generate the credentials when an AS is first set up and keep them when the configuration is updated.

**Comment by mlegner** [comment]
We need to be careful when an AS connects to an Attachment Point in a *different* ISD.
In that case, certificates and trc need to be updated.

**Comment by juagargi** [comment]
Closed per #277
