### ISSUE TITLE
Uncatched error ("missed pk value") in getUpdatesForAP for unknown ASes

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-coord#168]
There is an uncatched `http: panic service 127.0.0.1:35824: missed pk value` error in `getUpdatesForAP` in `controllers/api/scion_lab_ap.go`, specifically in FindRespondConnectionInfoByIA (Line 104 in controllers/api/scion_lab_ap.go) when calling FindSCIONLabASByIAString (Line 394 in models/scion_lab.go). 

The error arises when the provided AS list (e.g. by calling `update_gen.py` from scion-box) includes an AS that does not exist in the coordinator. This is, e.g., the case when the local gen folder and SCION coordinator differ.

**Comment by mlegner** [comment]
Fixed by #169.
