### ISSUE TITLE
SCIONLab repo

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-coord#171]
With the SCIONLab code distributed over several repositories (scion-coord, scion-box, scion-utilities, scion-web) I am wondering if it would be a good idea to combine these repos in one single scionlab repo

**Comment by mlegner** [comment]
I also think that we should consolidate all of this somewhat. However, it would make sense to keep the `scion-util` repository separate as this is also used in `scion-web`. As far as I know, `scion-web` is not used in SCIONLab anymore (at least not directly).
One option would be to move all contents of `scion-box` to a subdirectory of `scion-coord` and serve them from there.
