### ISSUE TITLE
VPN client certificate has to have a different CN per user and AS

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-coord#176]
We need the VPN server to assign a unique static IP address to each AS that connects.
But when the same user creates a second AS, the VPN client certificate CN will still contain only the email address of the user, and will be identical to the previous VPN client certificate the user had for their first AS.
This prevents the VPN server to assign a different static IP address per AS, because the server assigns IP addresses based on the client's certificate CN.

**Comment by mlegner** [comment]
Fixed by #177.
