### ISSUE TITLE
All services bind to localhost when selecting "Install on a dedicated SCION system"

### ISSUE THREAD

**Issue by xabarass** [netsec-ethz/scion-coord#181]
When we download configuration for native setup all services are binding on 127.0.0.1 This might be an issue if user wants to use newly installed AS from endhost machine.

**Comment by juagargi** [comment]
In PR #207 we now allow binding to 0.0.0.0, while we still keep the "Public" addresses the way we have been doing. It looks like this:
...
"BeaconService": {
    "bs1-1001-1": {
      "Bind": [
        {
          "L4Port": 31041,
          "Addr": "0.0.0.0"
        }
      ],
      "Public": [
        {
          "L4Port": 31041,
          "Addr": "127.0.0.1"
        }
      ]
    }
  },
...
For us to change the public addresses we just need to make a small change. The other possibility is this one:
...
"BeaconService": {
    "bs1-1001-1": {
      "Bind": [
        {
          "L4Port": 31041,
          "Addr": "0.0.0.0"
        }
      ],
      "Public": [
        {
          "L4Port": 31041,
          "Addr": "192.33.93.158"
        }
      ]
    }
  },
...
But this second version would break dedicated boxes behind NAT (as the services cannot bind to the public IP, but it's translated one).
For this I'm opening a new issue "support boxes behind NAT" #208
Please comment in this issue or that new one about how binding and service addressing should be better handled.
Reopen this issue if necessary.

**Comment by juagargi** [comment]
We (thanks @FR4NK-W ) have checked the code for the SCIONElement common parent class to the services, and it will not use the "Bind" option I added.
I'm reopening the issue.

**Comment by juagargi** [comment]
I'm going to modify the generated topologies only for the case of dedicated machines with public IP addresses. In that case the service will be located in its public IP. This breaks compatibility with NAT boxes (issue #208), but since dedicated machines are nevertheless "advanced" configurations for now, it should be okay.

**Comment by juagargi** [comment]
PR #209
