### ISSUE TITLE
Wrong URL in email

### ISSUE THREAD

**Issue by xabarass** [netsec-ethz/scion-coord#183]
Received emails (pass confirmation, AS created notification etc) contain url http://coord.scionproto.net:8080 
Protocol has to be changed to https and port number should be removed.

**Comment by mlegner** [comment]
Thanks for the notice. This is not a problem of the Coordinator but a wrong line in the configuration file.
I just fixed it and there should now be the correct links in the email, except for the protocol which is still http.
Unfortunately, currently the protocol can only be changed to https together with other features. I will open a new issue for that.

**Comment by stschwar** [comment]
While we are at it, it would be a nice addition if the mail that a user receives would contain the actual AS number for AS Creation Requests.
