### ISSUE TITLE
Protocol in email should be independent on whether native HTTPS is used

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#184]
Currently, the protocol of links in emails is determined by whether or not native HTTPS is enabled for the coordinator.
This should be changed as we often have a setup where the coordinator itself supports HTTP but there is another webserver that takes care of TLS.

**Comment by juagargi** [comment]
You are completely right, and I still have not fixed this!!

**Comment by juagargi** [comment]
Issued solved in #206
