### ISSUE TITLE
Support _ thousands separator

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-coord#196]
PR 1457 allows the use of _ as thousands separator. Libraries support e.g. 4294967400 or 4_294_967_400 .
We should allow the usage of such strings, as it makes life easier for the users when working with big AS ids.

https://github.com/scionproto/scion/pull/1457

**Comment by mlegner** [comment]
That's good news. On our side, only minor modifications should be necessary as we are already mostly relying on the library from the main codebase. We should probably have a look at `utility.IAString` function and the places where it is used however and also fix a "standard" AS format.
I would suggest always using the '_' separator when the AS has more than 3 digits.
