### ISSUE TITLE
Email message for creation / removal of AS is too generic

### ISSUE THREAD

**Issue by FR4NK-W** [netsec-ethz/scion-coord#212]
The email confirmation after creation / removal of an AS currently reads as follows:
`The infrastructure for your SCIONLab AS has been created. You are now able to use the SCION network through your AS.
Please visit https://www.scionlab.org/#/user for further details on the current status of your AS.`
`Your removal request has been processed. All infrastructure for your SCIONLab AS has been removed.
Please visit https://www.scionlab.org/#/user for further details on the current status of your AS.`

It would be helpful to include the ID of the AS concerned by the change as users can have at least up to two ASes in the standard configuration.

**Comment by mlegner** [comment]
Fixed by #213.
