### ISSUE TITLE
Coordinator must accept changes not fulfilled by update_gen

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-coord#220]
When a change from the Coordinator (e.g. detach an AS) cannot be fulfilled by update_gen, it should inform about it to the Coordinator.
Create / extend the API to do just that. After treating the failure, the Coordinator must not return this change as a pending change anymore.
update_gen side issue: https://github.com/netsec-ethz/scion-box/issues/35

**Comment by mlegner** [comment]
This is solved by #224.
