### ISSUE TITLE
Post review

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-coord#240]
https://github.com/netsec-ethz/scion-coord/pull/238

**Comment by FR4NK-W** [comment]
Empty issue, branch #238 Remap AS identity merged on Jul 2.

@juagargi
AS id remapping functionality should no longer be required, right?
Version change and the update script would take care of applying the coordinator view.

**Comment by juagargi** [comment]
I don't know what this issue is for. As @FR4NK-W mentioned, #238 was long merged, adding the possibility of remapping IDs.
