### ISSUE TITLE
Evaluate alternatives to OpenVPN

### ISSUE THREAD

**Issue by matzf** [netsec-ethz/scion-coord#270]
We are currently running an OpenVPN server in each attachment point to allow connecting user ASes behind firewalls, NATs etc. OpenVPN appears to be relatively resource hungry, and we've been experiencing some hard to reproduce and debug issues with clients being configured with the wrong IP and resulting broken tunnels (*). Rumor has it that [wireguard](https://www.wireguard.com/) is a newer, better and faster alternative. 

(*) One known bug with the OpenVPN usage in the APs is the following race condition: 
1) the user downloads the configuration. The VPN-IP for the client is chosen by the coordinator.
2) a) the AP runs updateGen and updates the VPN configuration for the client
     b) the user starts the VPN client
If b) happens before a), the client may receive a wrong IP.

**Comment by matzf** [comment]
### wireguard

* Relatively new, work in progress:
> You should not rely on this code

* UDP only! This may require some additional tunneling for firewalls.

* one simple configuration for NAT/firewall traversal persistence: `PersistentKeepalive = 25` will enable sending a keep-alive packet in 25s intervals.

* PKI, no config for crypto algorithms etc. Assumption is that (short!) keys can be distributed out of band. This fits our use case where the VPN keys are in fact generated centrally by the coordinator.

* much simpler to understand and configure than OpenVPN. I find this the most compelling point in favor of wireshark; it usually just works and if something doesn't work, wireguard is simple enough to have a good mental model for it and find out why things are not working. 

#### Performance tests
I ran various tests to compare wireguard with OpenVPN; since wireshark is implemented as a kernel module while OpenVPN is a mix of kernel modules and user space libraries, measuring and comparing performance is somewhat fiddly; the most reliable metric I found is to simply look at `mpstat` and consider `100-%idle`.

* a bandwidth test with `iperf3` showed ~2 times higher bandwidth achieved with wireguard than with OpenVPN (742Mbit/s for wireguard, 316Mbit/s for OpenVPN), with a similar CPU load on the server (~25%, i.e. one out of the four cores).
* a subsequent UDP test with limited bandwidth (`iperf3 -u -b300M`) shows *higher* CPU load for wireguard than for OpenVPN -- not sure how to make sense of this.
* I tried to simulate the load that a large number of connected user ASes would generate by running a UDP-echo server on the simulated AP and send udp packets at high rate from ~250 clients. 
  * wireguard: small CPU load on the AP (~6%)
  * OpenVPN: not run -- could not find a simple enough way to run multiple clients on one host

This performance comparison is somewhat inconclusive, but I have the impression that wireguard will at least not be *worse* than OpenVPN.

**Comment by FR4NK-W** [comment]
`most compelling point in favor of wireshark`, ` since wireshark is implemented as a kernel `
Major drawback: It gets confused with wireshark :smirk:
