### ISSUE TITLE
signature verification failed. Had to remove entries in gen-cache

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-coord#273]
It has happened, at least in two different occasions, that we were forced to remove entries in the `$SC/gen-cache` directory. This is of course a symptom that something else is wrong, as we don't issue new certificates for existing ASes, and thus the old certificates would still be valid.
Investigate as this is very probably an issue in the Coordinator and not one in scionproto.

**Comment by mlegner** [comment]
This issue is related to #135 which has been forgotten over the past few months.

**Comment by juagargi** [comment]
Removed `gen-cache` as well at all infrastructure nodes.
