### ISSUE TITLE
Old AS IDs in DB must be mapped or dropped

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-coord#283]
We still have many old style addresses in the DB. Those are typically held by ASes no longer in use, but not exclusively.

- We should send a message to the users to tell them that their AS IDs will be mapped to their new style equivalent.
- We should map them to the new style.

* What are the unforeseen consequences of this? (unforeseen so far, that is)

**Comment by FR4NK-W** [comment]
I think we should do that change as soon as possible, so that we can drop the remapping code.
ASes with the old AS IDs won't work with the current scionlab version, so we should remap them and remove the entries with the old address format.
