### ISSUE TITLE
No gen-certs/tls.pem

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scion-coord#310]
Due to some changes in the `scion.sh` script, the new VMs installed from the coordinator will not have the default certificate that some apps such as `pingpong` will require. Now, to build that file, we have to run `scion.sh topology`.
Change our installation script so that we generate these certificate when installing SCION.

**Comment by FR4NK-W** [comment]
Certificate generation was moved to cmd_topology and out of the main cmd_run in scion.sh:
https://github.com/scionproto/scion/blob/b5b14815cf52510b64c807e262d9a292e40c6274/scion.sh#L35
