### ISSUE TITLE
[SCIONLab] Create Vagrant image already including SCION and upload to Vagrant repo

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-coord#44]
The current implementation of our Vagrant configuration downloads a base Ubuntu 16.04 image and then installs and configures SCION at the setup phase.
As discussed with David Hausheer and @jonghoonkwon, it is possible to create an Ubuntu 16.04 image which already includes SCION installation and upload it to Vagrant repository (www.vagrantcloud.com).

This will reduce the required setup time of the VM on the user's side.

**Comment by ercanucan** [comment]
@hausheer as discussed, assigning this to you.

**Comment by mlegner** [comment]
Is this still planned @hausheer? 
As we now have the installation script by @xabarass, we may not really need a special vagrant box any more.
In that case, we could again use the standard ubuntu box.

**Comment by hausheer** [comment]
@mlegner The idea of this issue is to create a box that will have SCION included (except the gen folder) similar to the images for RaspberryPi and Odroid. It is not urgent, but it will speed up the setup of a new VM. I will take care of it.
