### ISSUE TITLE
[SCIONLab] Ability to serve the pure gen folder

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-coord#45]
Currently we serve the whole VM package including the gen folder, vagrant configurations etc.

As discussed with David Hausheer and @perrig, it will be a useful extension for users to be able to download the pure gen folder for their SCION ASes, so that they can run their ASes directly on a dedicated machine, without the use of a VM. This implies that the UI for this feature should not only ask the user to specify his/her public IP address but also the local IP address (which is currently set statically via the Vagrant configuration file) inside their NAT.

**Comment by mlegner** [comment]
Fixed by PR #136.
