### ISSUE TITLE
[SCIONLab] Connecting to multiple SCIONLab ASes

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-coord#46]
At the moment, the users of SCIONLab are connected to a fixed SCIONLab AS (1-7 in this case). As discussed with David Hausheer and @jonghoonkwon, the number of allowed SCIONLab ASes should be increased and the users should be able to choose which SCIONLab AS they want to connect to.

**Comment by mlegner** [comment]
Fixed by PR #136.
