### ISSUE TITLE
[SCIONLab] Ability to re-send verification email

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-coord#48]
Currently, scion-coord does not have a mechanism to re-send the verification email.
As discussed with @chaehni and David Hausheer, in case a user loses the verification email before he activates his account or the email delivery fails, it would be useful for the user to be able to re-request the verification email.

**Comment by ercanucan** [comment]
@chaehni as discussed, assigning this issue to you.

**Comment by mlegner** [comment]
Fixed by cbc0fbaba194e50b63f77bd4f071e043ac245937
