### ISSUE TITLE
[SCIONLab] Support for NATted use cases

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-coord#57]
As discussed with @hausheer, @perrig and @mlegner, one way to provide SCIONLab for NATted cases with changing IP addresses (such as home users) would be to use an OpenVPN-based approach. 
In such scenarios, designated SCIONLab ASes would run an instance of OpenVPN server. Each newly created SCIONLab VM (which would connect to such SCIONLabASes) would be generated with configuration to run an OpenVPN client.

**Comment by mlegner** [comment]
Fixed by 0a93ab76b341da0d47308e78ce0bede0eb26da28
