### ISSUE TITLE
[API] Entry point for receiving the signed certificate

### ISSUE THREAD

**Issue by silenteh** [netsec-ethz/scion-coord#6]
Once a core AS accepts the entrance of the newly created account, it needs to sign the certificate uploaded in issue #4 
At this point the rest API should also receive information about the core AS:
- Ip address
- Port

To recap, the REST API should allow to:
- [ ] Upload the signed certificate.
- [ ] Accept an IP address field.
- [ ] Accept a port field.

Ideally all this is done in once call.

**Comment by ercanucan** [comment]
Implemented in PR #21
