### ISSUE TITLE
[SCIONLab] Pre-approved invitation-based registration

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-coord#61]
As discussed with @hausheer, a feature we would like to add is pre-approved, invitation-based registration (with a link the user can click on).

Coordination service should provide a page for the administrator to able to provide a new user's email address and organization. When the "Invite" button is clicked, the new user should receive an email with a link similar to: https://coord.scionproto.net/#/register?email=user@organization.org&accountid=org

Pre-approved registrations do not need to go through email verification or Captcha.

**Comment by mlegner** [comment]
Fixed by PR #75.
