### ISSUE TITLE
[SCIONLab] Multiple VMs per-user, per-host

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-coord#70]
As discussed with @perrig, @hausheer and @mlegner, we would like to support multiple VMs per-user, with possibility to run them on the same host.

- The current implementation of scion-coord (DB, API, UI layers) assumes only one VM per user. This assumption must be relaxed.
- In order for the user to run multiple VMs on the same host, the Vagrant configuration generation also needs to be updated in terms of forwarded ports, VM names, etc.

**Comment by mlegner** [comment]
Fixed by PR #136.
