### ISSUE TITLE
[SCIONLab] Packaging as-viz into VMs

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion-coord#81]
As discussed with @perrig, downloaded VM configurations should contain SCION AS Visualization tool, so that the users can view the topology of the network.

This feature also requires the following configurations packaged into the VMs:
- Relevant `sciond` configuration.
- Relevant `endhost` configuration.

**Comment by mwfarb** [comment]
AS Visualization repo https://github.com/netsec-ethz/scion-viz is now public.

**Comment by mlegner** [comment]
Fixed by PR #100.
