### ISSUE TITLE
[SCIONLab] Decrease error verbosity

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#84]
Currently a lot of information is leaked through error messages in order to facilitate debugging.
For the "beta release" of SCIONLab this verbosity should be decreased, possibly at the same time adding a "debug" option to the configuration.

**Comment by ercanucan** [comment]
+1

**Comment by mlegner** [comment]
As already discussed in person with @hausheer, we could have two separate PRs:

1. Replace all error messages on the website with some showing less information.
2. In a second step adding a debug mode and/or error codes facilitating the debugging.
