### ISSUE TITLE
[SCIONLab] Fix and improve `run.sh` script

### ISSUE THREAD

**Issue by mlegner** [netsec-ethz/scion-coord#86]
There is a bug in `run.sh` where vagrant is reported to be installed when it is actually missing.
In addition, the script currently only supports mac os and ubuntu. Users of other linux distributions need to manually install vagrant and virtualbox.
It would be nice to automatize this for other distributions as well.

**Comment by juagargi** [comment]
There is the PR #195 that slightly modifies run.sh . We could quickly extend the script to at least check if virtualbox and vagrant are running with the minimum versions, and if not and the system is unsupported (Fedora, etc), print a message to let the user manually install them, and try again.
