### ISSUE TITLE
[SCIONBox] Add API function to initialize a new SCION box

### ISSUE THREAD

**Issue by philippmao** [netsec-ethz/scion-coord#89]
The function should receive the _IP address_, _MAC address_,  _source IP address_ from the SCION box via HTTPS. Compare _IP address_ and _source IP address_ to determine if box is behind a NAT. If the box is behind a NAT connect it to a SCIONLabserver similar to how a SCIONLabVM behind a Nat is connected.   
Else the function uses **IP geolocation** and the user credentials to determine the boxes ISD. Then queries its **database** to find potential neighbors and sends them to the box. 
Also we probably want a flag in the message that triggers a simplified call that either chooses neighbors for the box and then sends the gen folder or notifies the system admin to manually configure the box via ssh ( for the geneva box for example )

**Comment by mlegner** [comment]
Fixed by #131.
