### ISSUE TITLE
[SCIONBox] Add API function to connect a SCION box to the SCION net

### ISSUE THREAD

**Issue by philippmao** [netsec-ethz/scion-coord#90]
This function should receive a list of neighbors from the SCION box. The function then updates the **Database**, generates the gen folder and sends the gen folder to the SCION box.   
The ASes the box connects to, will be querying the Database similar to how the SCIONlabserver queries the database and also update their configuration accordingly.

**Comment by mlegner** [comment]
Fixed by #131.
