### ISSUE TITLE
[SCIONBox] Add database that stores ASes that a new box can connect to.

### ISSUE THREAD

**Issue by philippmao** [netsec-ethz/scion-coord#91]
This database should store all ASes to which a new box can connect to. Along with information like number of neighbors, core, border router IP addresses and ISD. Stored ASes can be SCION boxes or native ASes or SCIONLab servers.   
On the same topic ASes will be querying this Database to find out if a new AS wants to connect.

**Comment by mlegner** [comment]
We can probably expand/replace the existing SCIONLabServer database for this.

**Comment by mlegner** [comment]
This is fixed by #121.
